import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './prosemirror.css'

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-sans'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
      </head>
      <body className={`dark ${inter.className} bg-dark-3`} >
        {children}
      </body>
    </html>
  );
}
